name: example
description: A new Flutter project.

version: 1.0.0+1

publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  confetti:
    path: ../
  cupertino_icons: ^0.1.2
  flutter:
    sdk: flutter
  flutter_svg: ^0.22.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
